config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :badges
  end

  resources :user_badges, only: [:index]

  resources :contacts, only: [:new, :create, :show, :index] do
    get 'contacts', to: 'contacts#new'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index, only: [:show, :index] do
      resources :answers, shallow: true, except: :index, only: [:show, :index]
    end
    get '/tests/:category/:title', to: 'test#search'
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  validates :image_url, :name, presence: true
  validates :image_url, format: URI::regexp(%w[http https])

  CATEGORIES = ["All Backend tests compleated", "Test passed from the first attempt", "Level 1 compleated" ]

  def rule
    case name
    when CATEGORIES[0]
      "all_backend_tests_completed"
    when CATEGORIES[1]
      "passed_from_first_attempt"
    when CATEGORIES[2]
      "level_compleated"
    end
  end

  def all_backend_tests_completed_award?(badge_value)
    badge_value[:all_backend_tests_completed]
  end

  def passed_from_first_attempt_award?(badge_value)
    badge_value[:passed_from_first_attempt]
  end

  def level_compleated_award?(badge_value)
    badge_value[:level_compleated]
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < ApplicationController
  before_action :set_badge, only: %i[ show edit update destroy ]

  # GET /badges or /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1 or /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges or /badges.json
  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: "Badge was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /badges/1 or /badges/1.json
  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), notice: "Badge was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /badges/1 or /badges/1.json
  def destroy
    @badge.destroy
    redirect_to admin_badges_url, notice: "Badge was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_badge
    @badge = Badge.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def badge_params
    params.require(:badge).permit(:name, :image_url)
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, badge]) do |form| %>
  <% if badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
        <% badge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br>
    <p>
      <%= form.select :name, options_for_select(Badge::CATEGORIES), prompt: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>

  <div type="submit">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Show', admin_badge_path(@badge) %> |
<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Badges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.name %></td>
        <td><%= image_tag badge.image_url, style: 'height:50px;width:80px;' %></td>
        <td><%= link_to 'Show', [:admin, badge] %></td>
        <td><%= link_to 'Edit', edit_admin_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', [:admin, badge], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_admin_badge_path %>

app/views/admin/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @badge.image_url %>
</p>

<%= link_to 'Edit', edit_admin_badge_path(@badge) %> |
<%= link_to 'Back', admin_badges_path %>