config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :badges
  end

  resources :user_badges, only: [:index]

  resources :contacts, only: [:new, :create, :show, :index] do
    get 'contacts', to: 'contacts#new'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index, only: [:show, :index] do
      resources :answers, shallow: true, except: :index, only: [:show, :index]
    end
    get '/tests/:category/:title', to: 'test#search'
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
  validate :number_of_question_answers, on: :create
  scope :correct, -> { where(correct: true) }

  def number_of_question_answers
    existing_answers = question.answers.count
    errors.add(:question, 'Cannot have more then 4 answers') if existing_answers >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  validates :image_url, :name, presence: true
  validates :image_url, format: URI::regexp(%w[http https])

  CATEGORIES = ["All Backend tests compleated", "Test passed from the first attempt", "Level 1 compleated" ]

  def rule
    case name
    when CATEGORIES[0]
      "all_backend_tests_completed"
    when CATEGORIES[1]
      "passed_from_first_attempt"
    when CATEGORIES[2]
      "level_compleated"
    end
  end

  def all_backend_tests_completed_award?(badge_value)
    badge_value[:all_backend_tests_completed]
  end

  def passed_from_first_attempt_award?(badge_value)
    badge_value[:passed_from_first_attempt]
  end

  def level_compleated_award?(badge_value)
    badge_value[:level_compleated]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
  default_scope { order('title ASC') }
  validates :title, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :user, presence: true
  validates :question, presence: true

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists
  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :questions, dependent: :destroy

  scope :by_level, ->(level) { where(level: level) }
  scope :simple_level, -> { where(level: 0..1) }
  scope :middle_level, -> { where(level: 2..4) }
  scope :difficult_level, -> { where(level: 5..Float::INFINITY) }
  scope :join_with_categories, lambda { |category_title|
    joins('JOIN categories ON tests.category_id = categories.id').where('categories.title' => category_title)
  }
  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  before_validation :convert_duration_to_seconds

  def correct_answers
    Answer.joins(:question).where('test_id = ?', id).where(correct: true)
  end

  def convert_duration_to_seconds
    self.duration = Time.parse(duration).seconds_since_midnight
  end

  class << self
    def titles_by_category(category_title)
      join_with_categories(category_title)
        .order('categories.title ASC').pluck(:title)
    end
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: 'current_question_id', optional: true

  before_validation :before_validation_set_first_question, on: :create

  TEST_PASS_BENCHMARK = 85

  def test_attempts
    TestPassage.joins(:test).where(test_id: test.id, user_id: user.id)
  end

  def same_categories_tests_passed
    user.test_passages.joins(:test).where(passed: true).where('tests.category_id = ?', test.category.id).distinct
  end

  def update_test_passage_status
    update_attribute(:passed, success?)
  end

  def compleated?
    current_question.nil? || expired?
  end

  def accept!(answer_ids)
    self.correct_question += 1 if correct_answer?(answer_ids)

    self.current_question = next_question
    save!
  end

  def success?
    correct_answers_percentage >= TEST_PASS_BENCHMARK && !expired?
  end

  def expired?
    time_left.negative?
  end

  def time_left
    deadline_time.to_i - Time.now.to_i
  end

  def deadline_time
    created_at + test.duration
  end

  def correct_answers_percentage
    all_questions = test.questions.count
    test.correct_answers.count / all_questions * 100
  end

  def progress
    ((test.questions.index(current_question).to_f / test.questions.count.to_f) * 100).to_i
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.count == correct_answers.where(id: answer_ids).count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable,
    :confirmable
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists
  has_many :user_badges
  has_many :badges, through: :user_badges
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: true

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.now.year
  end

  def github_url(author, repo)
    link_to(author, repo, _blank: true)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/flash_helper.rb
module FlashHelper

  def flash_class(level)
    level = level.to_sym
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-primary"
    end
  end

  def flash_messeges
    flash_alert
    flash_errors
  end

  def flash_alert
    content_tag(:p, flash[:alert], { class: 'alert alert-error' }) if flash[:alert]
  end

  def flash_errors
    flash[:errors]&.each_with_index do |_item, index|
      content_tag(:p, flash[:errors][index], { class: 'alert alert-danger' })
    end
  end
end

app/helpers/nav_helper.rb
module NavHelper

  def user_home_path
    user_signed_in? && current_user.admin? ? admin_tests_path : root_path
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    header_start = question.persisted? ? 'Edit' : 'Create New'
    "#{header_start} #{question.test.title} Question"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_header.html.erb
<div class="header">
  <% if user_signed_in? %>
    <%= link_to 'TestGuru', root_path %>|
    <%= link_to 'All tests list', tests_path %>|
    <%= link_to 'Achieved Badges', user_badges_path %>|
    <%= link_to 'Manage Badges', admin_badges_path %>
    </p>
  <% end %>
</div>

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">

  <% if user_signed_in? %>
    <%= link_to 'TestGuru Admin Panel', admin_tests_path, class: 'navbar-brand' %>

    <span class="navbar-text">
      Welcome, <%= current_user.email %> Guru |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    </span>
  <% else %>
    <span class="navbar-text">
      <%= link_to 'TestGuru', tests_path, class: 'navbar-brand' %>
      <%= link_to "Log in", new_session_path(resource_name) %> |
      <%= link_to "Sign up", new_registration_path(resource_name) %>
    </span>
  <% end %>
</nav>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=devise-width, initial-scale=1, shrink-to-fit=no">

		<title>Admin Panel | TestGuru</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<%= render "admin/nav" %>
		<%= render "admin/header" %>
		<%= render "shared/flash" %>
		<%= yield %>
	</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=devise-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/nav" %>
    <div class="container">
      <%= render "shared/flash" %>
      <%= render "shared/header" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_message.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%=  content_tag :div, sanitize(message), class: flash_class(key) %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p><%= link_to 'Связатся с нами', new_contact_path %></p>
  <p>Учебный проект в онлайн-школе <a href="https://thinknetica.com/" target="_blank">Thinknetica</a> <%= current_year %>
  </p>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <% if user_signed_in? %>
    <%= link_to 'TestGuru', root_path %>
    <%= link_to 'All tests list', tests_path %>
    <%= link_to 'Badges', user_badges_path %>
    </p>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', user_home_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= current_user.first_name %></b>Guru |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path(resource_name) %> |
      <%= link_to "Sign up", new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>