config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :badges
  end

  resources :user_badges, only: [:index]

  resources :contacts, only: [:new, :create, :show, :index] do
    get 'contacts', to: 'contacts#new'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index, only: [:show, :index] do
      resources :answers, shallow: true, except: :index, only: [:show, :index]
    end
    get '/tests/:category/:title', to: 'test#search'
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists
  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: 'current_question_id', optional: true

  before_validation :before_validation_set_first_question, on: :create

  TEST_PASS_BENCHMARK = 85

  def test_attempts
    TestPassage.joins(:test).where(test_id: test.id, user_id: user.id)
  end

  def same_categories_tests_passed
    user.test_passages.joins(:test).where(passed: true).where('tests.category_id = ?', test.category.id).distinct
  end

  def update_test_passage_status
    update_attribute(:passed, success?)
  end

  def compleated?
    current_question.nil? || expired?
  end

  def accept!(answer_ids)
    self.correct_question += 1 if correct_answer?(answer_ids)

    self.current_question = next_question
    save!
  end

  def success?
    correct_answers_percentage >= TEST_PASS_BENCHMARK && !expired?
  end

  def expired?
    time_left.negative?
  end

  def time_left
    deadline_time.to_i - Time.now.to_i
  end

  def deadline_time
    created_at + test.duration
  end

  def correct_answers_percentage
    all_questions = test.questions.count
    test.correct_answers.count / all_questions * 100
  end

  def progress
    ((test.questions.index(current_question).to_f / test.questions.count.to_f) * 100).to_i
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.count == correct_answers.where(id: answer_ids).count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]
  def show
    if @test_passage.current_question.nil?
      redirect_to tests_path
    end
  end

  def result

  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.compleated?
      @test_passage.update_test_passage_status
      UserBadgeService.new(@test_passage.id).call
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    flash_options = {}

    github_gist = save_gist_on_github
    gist_url = github_gist.response['html_url']

    if github_gist.sucess? && new_gist(github_gist.response).save
      flash_options = { notice: view_context.link_to(t('.success', url: gist_url), gist_url, {target: "_blank"})}
    else
      flash_options = { alert: t('.failure')}
    end

    redirect_to @test_passage, flash_options
  end

  private

  def save_gist_on_github
    git_question_service = GistQuestionService.new
    git_question_service.create_gist(@test_passage.current_question)
    git_question_service
  end

  def new_gist(github_gist)
    current_user.gists.new( question_id: @test_passage.current_question.id,
                           github_gist_id: github_gist['id'],
                           html_url: github_gist['html_url']
                          )
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result_outcome(test_passage)
    if test_passage.success?
      { message: 'Test passed successfully', status: 'test_passed' }
    else
      { message: 'Test failed', status: 'test_failed' }
    end
  end
end

app/views/test_passages/result.html.erb
<h1> The <%= t('.header', title: @test_passage.test.title)  %> </h1>
<div class="test_result" id=<%= result_outcome(@test_passage)[:status] %>>
  <h2> Your score is <%= @test_passage.correct_answers_percentage %>
  <h2>  <%= result_outcome(@test_passage)[:message] %> </h2>
</div>

app/views/test_passages/show.html.erb
<h1>Passing the test <%= @test_passage.test.title %></h1>
<p>
  <%= content_tag :div, @test_passage.progress, class: 'progress', data: { current_progress: @test_passage.progress } do  %>
    <div class="progress-bar" role="progressbar"  aria-valuemin="0" aria-valuemax="100"></div>
  <% end %>
</p>

<p>
  <%= content_tag :div, class: 'timer', data: { deadline: @test_passage.deadline_time.httpdate } do  %>
    <div id="time-count"></div>
  <% end %>
</p>

<p>
  <%= @test_passage.current_question.body %>
</p>

<%= form_with url: test_passage_path(@test_passage), method: :put, local: true, id: "test_passage_form"  do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}",  include_hidden: false %>
      <%= b.label %>
    </p>
  <% end %>
  <p><%= link_to 'Gist Questions', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next', class: "btn btn-primary", id: "submit-button" %></p>
<% end %>