config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :badges
  end

  resources :user_badges, only: [:index]

  resources :contacts, only: [:new, :create, :show, :index] do
    get 'contacts', to: 'contacts#new'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index, only: [:show, :index] do
      resources :answers, shallow: true, except: :index, only: [:show, :index]
    end
    get '/tests/:category/:title', to: 'test#search'
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
  validate :number_of_question_answers, on: :create
  scope :correct, -> { where(correct: true) }

  def number_of_question_answers
    existing_answers = question.answers.count
    errors.add(:question, 'Cannot have more then 4 answers') if existing_answers >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < ApplicationController

  before_action :set_question, only: %i[index show new create]
  before_action :set_answer, only: %i[edit update destroy]

  # GET /tests or /tests.json
  def index
    @answers = @question.answers
  end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@question), notice: 'Answer was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question), notice: 'Answer was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question = @answer.question
    @answer.destroy
    redirect_to admin_question_url(@question), notice: 'Answer was successfully destroyed.'
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  ## Only allow a list of trusted parameters through.
  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

end

app/views/admin/answers/_form.html.erb
<%= form_with model: @answer, url: @answer.new_record? ? admin_question_answers_path(@question) : admin_answer_path(@answer), local: true do |form| %>
  <div class="form-group">
    <%= form.label :body, "Write an answer body"%>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <div class="form-check">
    <%= form.label :correct, class: "form-check-label" do %>
      Correct Answer
      <%= form.check_box :correct,  input_html: {class: "form-check-input", checked: @answer.correct} %>
    <% end %>
  </div>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "Save answer", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
Edit Answer<br>
<h1>
  <%= @answer.body%>
</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@answer.question) %>